CREATE TABLE IF NOT EXISTS jobs (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    title             TEXT NOT NULL,
    company           TEXT NOT NULL,
    location          TEXT,
    url               TEXT UNIQUE NOT NULL,
    source            TEXT DEFAULT 'greenhouse',
    date_found        TEXT,
    jd_text           TEXT,
    score             INTEGER,
    decision          TEXT,
    confidence        INTEGER,
    skills_score      INTEGER,
    experience_score  INTEGER,
    domain_score      INTEGER,
    location_score    INTEGER,
    seniority_score   INTEGER,
    matched_skills    TEXT,
    missing_skills    TEXT,
    red_flags         TEXT,
    reasoning         TEXT,
    status            TEXT DEFAULT 'new',
    date_applied      TEXT,
    package_path      TEXT
);
